image: python:3.9

# Install required packages
tasks:
  - command: "pip install pandas matplotlib"
  - command: "cp assets/sourcestack-data-id_bcu86flyul.csv /workspace/assets/sourcestack-data-id_bcu86flyul.csv"

# Open the data_analysis.py file
vscode:
  extensions:
    - ms-python.python

# Preview the bar plot in the Gitpod preview
ports:
  - port: 8000
    onOpen: open-preview